#!/bin/bash
echo "CWM Standalone Launcher Trigger $1 selected"
echo "(*) Downloading platform-tools"
rm -rf platform-tool*
wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip -q
echo "(!) Downloaded platform-tools"
unzip platform-tools-latest-linux.zip
echo "(!) Unzipped platform-tools"
echo "(*) Starting ADB.."
./platform-tools/adb kill-server
./platform-tools/adb start-server
echo "(*) ADB started, authorize your device if you get the prompt"
./platform-tools/adb wait-for-device
./platform-tools/adb reboot bootloader
echo "(!) Trigger launched."
echo "[INFO] You will not be able to access ADB or this launcher when you are in fastboot mode. For fastboot mode however, if a trigger fails, run ./trigger (1, 2, 3, or 4) to try again."
./trigger $1

